"""OpenPilot metadata protocol exports."""

from metadata.artifacts import (
    CodeArtifactMetadata,
    CommandArtifactMetadata,
    EmbeddingArtifactMetadata,
    FileArtifactMetadata,
    SearchArtifactMetadata,
    TextArtifactMetadata,
)
from metadata.base import (
    CorrelationInfo,
    JsonValue,
    MetadataBase,
    MetadataKind,
    MetadataSource,
    ensure_metadata,
    metadata_summary,
)
from metadata.bugfix import BugFixAttemptMetadata, BugFixResultMetadata
from metadata.data import CollectedDataMetadata, PresentationMetadata, ProcessedDataMetadata
from metadata.project import (
    AutonomyDecisionMetadata,
    EnvironmentSyncMetadata,
    ImprovementCandidateMetadata,
    ImprovementAnalysisMetadata,
    ProjectDiagnosisMetadata,
    ProjectDimensionAssessmentMetadata,
    ProjectObjectiveMetadata,
    ProductIntentMetadata,
    ProjectStateMetadata,
    ReferenceInsightMetadata,
    SuccessMetricMetadata,
    ValidationIssueMetadata,
)
from metadata.results import (
    ArtifactMetadata,
    FailureMetadata,
    ResultStatus,
    TaskResultMetadata,
    ToolResultMetadata,
    metadata_tool_result,
    payload_to_artifact,
    tool_result_payload,
)
from metadata.routing import ExecutionRoute, TaskRouteMetadata
from metadata.runtime import (
    AgentExecutionMetadata,
    ExecutionContextMetadata,
    LLMRequestMetadata,
    LLMResponseMetadata,
    LogEventMetadata,
    ModuleExecutionMetadata,
    ToolExecutionEnvelopeMetadata,
)
from metadata.tooling import (
    ToolChainMetadata,
    ToolContractMetadata,
    ToolInputMetadata,
    ToolSelectionMetadata,
    artifact_to_tool_input,
)
from metadata.warnings import WarningCheckResultMetadata, WarningItemMetadata

__all__ = [
    "ArtifactMetadata",
    "BugFixAttemptMetadata",
    "BugFixResultMetadata",
    "CodeArtifactMetadata",
    "CommandArtifactMetadata",
    "CorrelationInfo",
    "CollectedDataMetadata",
    "EmbeddingArtifactMetadata",
    "EnvironmentSyncMetadata",
    "ExecutionContextMetadata",
    "FailureMetadata",
    "FileArtifactMetadata",
    "AgentExecutionMetadata",
    "AutonomyDecisionMetadata",
    "ExecutionRoute",
    "ImprovementCandidateMetadata",
    "ImprovementAnalysisMetadata",
    "JsonValue",
    "LLMRequestMetadata",
    "LLMResponseMetadata",
    "LogEventMetadata",
    "MetadataBase",
    "MetadataKind",
    "MetadataSource",
    "ModuleExecutionMetadata",
    "PresentationMetadata",
    "ProcessedDataMetadata",
    "ProjectDiagnosisMetadata",
    "ProjectDimensionAssessmentMetadata",
    "ProjectObjectiveMetadata",
    "ProductIntentMetadata",
    "ProjectStateMetadata",
    "ReferenceInsightMetadata",
    "payload_to_artifact",
    "ResultStatus",
    "SearchArtifactMetadata",
    "TaskResultMetadata",
    "TaskRouteMetadata",
    "TextArtifactMetadata",
    "ToolChainMetadata",
    "ToolContractMetadata",
    "ToolExecutionEnvelopeMetadata",
    "ToolInputMetadata",
    "ToolResultMetadata",
    "ToolSelectionMetadata",
    "SuccessMetricMetadata",
    "ValidationIssueMetadata",
    "WarningCheckResultMetadata",
    "WarningItemMetadata",
    "artifact_to_tool_input",
    "ensure_metadata",
    "metadata_summary",
]
